name: check-code-and-run-tests

on:
  push:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

  pull_request:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

jobs:
  check-and-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache venv
        id: code-check-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: code-check-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.code-check-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Check code style
        run: poetry run poe check:style

      - name: Check lint
        run: poetry run poe check:lint

      - name: Check security issues
        run: poetry run poe check:security

      - name: Check shell scripts
        run: |
          sudo apt-get install -y shellcheck
          shellcheck tests/test.sh

      - name: Install system dependencies
        run: sudo apt-get install -y figlet stow

      - name: Run tests
        run: |
          cd tests
          ./test.sh
