name: Code quality checks

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  code-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install poetry
        uses: snok/install-poetry@v1.3.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache venv
        id: code-check-cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: code-check-python-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.code-check-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Check code style
        run: poetry run poe check:style

      - name: Check lint
        run: poetry run poe check:lint

      - name: Check security issues
        run: poetry run poe check:security

      - name: Check for dead code
        run: poetry run poe check:deadcode

      - name: Check shell scripts
        run: |
          sudo apt-get install -y shellcheck
          shellcheck tests/test.sh
